/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winguo_testbugly_jni_NdkJniUtils */

#ifndef _Included_com_winguo_testbugly_jni_NdkJniUtils
#define _Included_com_winguo_testbugly_jni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winguo_testbugly_jni_NdkJniUtils
 * Method:    nativeGenerateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL native_generate_key
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL addCalc
  (JNIEnv *, jobject, jint,jint);

/*
 * Class:     com_winguo_testbugly_jni_MonitorActivty
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL startMonitor
(JNIEnv *env, jobject obj);

/*
 * Class:     com_winguo_testbugly_jni_MonitorActivty
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL stopMonitor
(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
